[package]
name = "rustc_codegen_pliron"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["dylib"]

[dependencies]
rsasm = { version = "0.1.3", default-features = false, features = ["x86", "aarch64"] }
gimli = { version = "0.33", default-features = false, features = ["std", "write"] }
pliron = { path = "vendor/pliron", default-features = false, features = ["std"] }
pliron-llvm = { path = "vendor/pliron/pliron-llvm", default-features = false, features = ["std"] }
cranelift-codegen = { version = "0.135.5", default-features = false, features = ["std", "unwind", "host-arch"] }
cranelift-frontend = "0.135.5"
cranelift-module = "0.135.5"
cranelift-object = "0.135.5"
target-lexicon = "0.13"
object = { version = "0.39", default-features = false, features = ["std", "read_core", "write", "elf"] }
smallvec = "1"
egg = "0.10"
waffle = "0.3.2"

[workspace]
exclude = ["vendor"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[package.metadata.rust-analyzer]
rustc_private = true
