[package]
name = "pliron_bevy_game"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
pliron_hot = { path = "../pliron-hot" }
bevy = { version = "0.17", default-features = false, features = ["bevy_window", "bevy_winit", "bevy_render", "bevy_core_pipeline", "bevy_sprite", "bevy_sprite_render", "bevy_log", "bevy_text", "default_font", "x11", "std", "multi_threaded"] }
